//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyStock.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Sup
    {
        public int SuplierID { get; set; }
        public string EmployeeID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionID { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual PurchasesBill PurchasesBill { get; set; }
    }
}
