//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyStock.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyStockEntities2 : DbContext
    {
        public PharmacyStockEntities2()
            : base("name=PharmacyStockEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emp_Sup> Emp_Sup { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchasesBill> PurchasesBills { get; set; }
        public virtual DbSet<purchesBillDetail> purchesBillDetails { get; set; }
        public virtual DbSet<SaleBillDetail> SaleBillDetails { get; set; }
        public virtual DbSet<SalesBill> SalesBills { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
