//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyStock.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasesBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchasesBill()
        {
            this.Emp_Sup = new HashSet<Emp_Sup>();
            this.purchesBillDetails = new HashSet<purchesBillDetail>();
        }
    
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonPhone { get; set; }
        public string EmployeeNationalID { get; set; }
        public Nullable<double> TotalPriceBeforeDiscount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> TotalPriceAfterDiscount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Sup> Emp_Sup { get; set; }
        public virtual employee employee { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchesBillDetail> purchesBillDetails { get; set; }
    }
}
