//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyStock.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesBill()
        {
            this.SaleBillDetails = new HashSet<SaleBillDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public double TatalPriceBeforeDiscount { get; set; }
        public double discount { get; set; }
        public double TotalPriceAfterDiscount { get; set; }
        public string EmployeeNationalID { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleBillDetail> SaleBillDetails { get; set; }
    }
}
