//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyStock.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleBillDetail
    {
        public int ProductCode { get; set; }
        public string ProductName { get; set; }
        public int SaleBillID { get; set; }
        public double ProductPrice { get; set; }
        public int Quantity { get; set; }
        public double TotalPrice { get; set; }
        public int ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesBill SalesBill { get; set; }
    }
}
